name = "websocket-relay-server"
main = "src/index.ts"
compatibility_date = "2023-03-11"

[durable_objects]
bindings = [{ name = "WSR", class_name = "WebSocketRelay" }]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketRelay"]
